In [66]:
import torch 
from torch.autograd import Variable
import numpy as np
batch_size = 1
max_length = 1
hidden_size = 2
n_layers = 1
N=10

rnn = torch.nn.RNN(input_size = 1, hidden_size=hidden_size, num_layers=n_layers, batch_first=True)
optimizer = torch.optim.Adam(rnn.parameters(), lr=0.9)   # optimize all parameters
loss_func = torch.nn.BCELoss() 
x = torch.FloatTensor([0,1,1,0,0,0,1,1,0,0]).resize_(N,1,1)
y = np.array([[1,0],[1,0],[1,0],[0,1],[1,0],[0,1],[0,1],[0,1],[1,0],[0,1]]).reshape((N,1,2))
print(y)
h0 = torch.randn(n_layers, N, 1)
output = None
for i in range(10):
    xi = Variable(x[i].resize_(1,1,1))
    yi = Variable(torch.FloatTensor( y[i]).resize_(1,1,2))
    output,_ = rnn(xi)
    print(output)
    loss= loss_func(output, yi)   # cross entropy loss
    optimizer.zero_grad()           # clear gradients for this training step
    loss.backward()                 # backpropagation, compute gradients
    optimizer.step()                # apply gradients
print(output)
test_output, _ = rnn(x)
pred_y = torch.max(test_output, 1)[1].data.numpy().squeeze()
print(pred_y, 'prediction number')
print(y, 'real number')

[[[1 0]]

 [[1 0]]

 [[1 0]]

 [[0 1]]

 [[1 0]]

 [[0 1]]

 [[0 1]]

 [[0 1]]

 [[1 0]]

 [[0 1]]]
tensor([[[ 0.0367, -0.6940]]], grad_fn=<TransposeBackward1>)


RuntimeError: all elements of input should be between 0 and 1